name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true

jobs:
  publish-homebrew:
    runs-on: ubuntu-latest
    if: github.repository == 'heyimusa/go-terraform-linter'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          
      - name: Set Version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          elif [ -n "${{ github.ref_name }}" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=v1.0.0" >> $GITHUB_ENV
          fi
          echo "Using version: $VERSION"
      
      - name: Update Homebrew Tap
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: go-terraform-linter
          formula-path: Formula/go-terraform-linter.rb
          homebrew-tap: heyimusa/homebrew-go-terraform-linter
          base-branch: main
          create-pullrequest: false
          download-url: https://github.com/heyimusa/go-terraform-linter/releases/download/${{ env.VERSION }}/go-terraform-linter-darwin-amd64
          commit-message: |
            go-terraform-linter ${{ env.VERSION }}
            
            Automatically updated by GitHub Actions
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          HOMEBREW_NO_AUTO_UPDATE: 1

  publish-snap:
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled - waiting for snap name approval
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build
      
      - name: Upload to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
        continue-on-error: true
      
      - name: Snap Upload Status
        if: failure()
        run: |
          echo "⚠️ Snap upload failed. This is likely because:"
          echo "1. The snap name 'go-terraform-linter' is not registered"
          echo "2. You need to register it at https://snapcraft.io/register"
          echo "3. Or the SNAPCRAFT_TOKEN is not set correctly"

  publish-chocolatey:
    runs-on: windows-latest
    if: github.repository == 'heyimusa/go-terraform-linter'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      
      - name: Set Version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            $env:VERSION = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_name }}" -ne "") {
            $env:VERSION = "${{ github.ref_name }}"
          } else {
            $env:VERSION = "1.0.0"
          }
          echo "VERSION=$env:VERSION" >> $env:GITHUB_ENV
          echo "Using version: $env:VERSION"
      
      - name: Generate Package
        run: make chocolatey
        env:
          VERSION: ${{ env.VERSION }}
      
      - name: Build Chocolatey Package
        run: |
          cd packages/chocolatey
          choco pack go-terraform-linter.nuspec
      
      - name: Publish to Chocolatey
        run: |
          choco apikey --key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org/
          $nupkg = Get-ChildItem packages/chocolatey/*.nupkg | Select-Object -First 1
          if ($nupkg) {
            choco push $nupkg.FullName --source https://push.chocolatey.org/
          } else {
            Write-Error "No .nupkg file found in packages/chocolatey/"
            exit 1
          } 